### ISSUE TITLE
不显示消息

### ISSUE THREAD

**Issue by yuangezhizao** [ma6254/cqhttp_webui#3]
rt，消息频率有数值，但是看不到消息
![image](https://user-images.githubusercontent.com/16861681/44439118-db9e7b80-a5f4-11e8-9754-232c0e7a20bf.png)

**Comment by ma6254** [comment]
请提供下console的输出，以及这个错误的重现方法

**Comment by ma6254** [comment]
## 原因
 [src/cqcode/index.js:34](https://github.com/ma6254/cqhttp_webui/blob/master/src/cqcode/index.js#L34)大概是因为text的类型为array而不是string

## 暂时的解决方案
 在 [配置文件说明](https://cqhttp.cc/docs/4.4/#/Configuration)中
有一项为`post_message_format`请将其设置为`string`，而不是`array`

## TODO
后面的更新中将会识别text类型，分别处理
